pipeline {
    agent any
    tools {
        maven "Maven 3.9.9"
    }
    
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn -B -DskipTests clean package"
                }
            }
        }
        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh 'mvn test'
                }
            }
        }
        stage("Complete") {
            steps {
                echo "Completed Stage!"
                }
            }
        }   
    }
}
